// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIZnMsED0brKLvYVzg2YABzsJ78dmCZIU',
    appId: '1:273715211110:web:0d203609703a5f2072f6a7',
    messagingSenderId: '273715211110',
    projectId: 'govistays-hillsidehs-1418',
    authDomain: 'govistays-hillsidehs-1418.firebaseapp.com',
    storageBucket: 'govistays-hillsidehs-1418.firebasestorage.app',
    measurementId: 'G-S692NQ68SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi1J8jRN5dRNXo2yiuGOOFc9aqMpUAF3U',
    appId: '1:273715211110:android:d5043dcef7459d8d72f6a7',
    messagingSenderId: '273715211110',
    projectId: 'govistays-hillsidehs-1418',
    storageBucket: 'govistays-hillsidehs-1418.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNOmirjWh3BUVQhEIUk2hdsbh6rhojLdQ',
    appId: '1:273715211110:ios:346c52511ea38b2972f6a7',
    messagingSenderId: '273715211110',
    projectId: 'govistays-hillsidehs-1418',
    storageBucket: 'govistays-hillsidehs-1418.firebasestorage.app',
    iosBundleId: 'com.example.govistays',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNOmirjWh3BUVQhEIUk2hdsbh6rhojLdQ',
    appId: '1:273715211110:ios:346c52511ea38b2972f6a7',
    messagingSenderId: '273715211110',
    projectId: 'govistays-hillsidehs-1418',
    storageBucket: 'govistays-hillsidehs-1418.firebasestorage.app',
    iosBundleId: 'com.example.govistays',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIZnMsED0brKLvYVzg2YABzsJ78dmCZIU',
    appId: '1:273715211110:web:cfda018cf156936e72f6a7',
    messagingSenderId: '273715211110',
    projectId: 'govistays-hillsidehs-1418',
    authDomain: 'govistays-hillsidehs-1418.firebaseapp.com',
    storageBucket: 'govistays-hillsidehs-1418.firebasestorage.app',
    measurementId: 'G-LK0TH8STNL',
  );
}
